[package]
name = "derive-where"
version = "0.1.0"
edition = "2018"
rust-version = "1.33.0"
description = "Deriving with custom trait bounds"
documentation = "https://docs.rs/derive-where"
readme = "README.md"
repository = "https://github.com/ModProg/derive-where"
license = "MIT OR Apache-2.0"
keywords = ["derive", "macro"]
categories = ["rust-patterns", "no-std"]
include = [
	"src/**/*",
	"Cargo.toml",
	"LICENSE-*",
	"README.md"
]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
