[package]
name = "derive-where"
version = "0.1.0"
edition = "2021"
# rust-version
description = "Deriving with custom trait bounds"
documentation = "https://docs.rs/derive-where"
readme = "README.md"
repository = "https://github.com/ModProg/derive-where"
license = "MIT OR Apache-2.0"
# keywords
# categories
include = [
	"src/**/*",
	"Cargo.toml",
	"LICENSE-*",
	"README.md"
]

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = "1"
