format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
newline_style = "Unix"
unstable_features = true
wrap_comments = true
