name: Audit

on: [push, pull_request]

jobs:
  rustfmt:
    name: rustfmt

    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/cargo-audit
          key: cargo-audit
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        run: cargo audit -D warnings
